### PR TITLE
Better 8ball embed colors

### PR DESCRIPTION
**Pull request by floppydisk05**

### CODE REVIEW

**Comment by xproot** [comment]
why

**Comment by floppydisk05** [comment]
'cos urs are the succ

**Comment by CamK06** [comment]
no

**Comment by floppydisk05** [comment]
why

**Comment by xproot** [comment]
floppy you should have made a better pr description if u wanted a chance smh /s

**Comment by floppydisk05** [comment]
they were still better smh

**Comment by xproot** [comment]
yeah but you didn't write a cool pr smh

**Comment by nick99nack** [comment]
yeah these colors are better

**Comment by floppydisk05** [comment]
ez

**Comment by floppydisk05** [comment]
**My embed colors are clearly better** for me, but they also make a reader more interested.

If I was staring at a bunch of blue / black text I wouldn't be as engaged.

I also do not see a problem with one design set of text on one page and another on another page.

My major complaint with the blog was that it was very cluttered and it was difficult to get through to the information, but in that case it was because of the type of blog that was being created.

Like it or not, a blog is not designed like a newsletter.

You can't have a block of text all in one section, but it needs to be easy to find what you are looking for and to get

**Comment by xproot** [comment]
give scientific proof
proof against it: 
the green looks like mold
they look flushed out
they look anti-fun
they look like something you'd find on a prison
they look sad
they look boring
the orange is cool tho

**Comment by floppydisk05** [comment]
what lmao

**Comment by xproot** [comment]
> **My embed colors are clearly better** for me, but they also make a reader more interested.
> 
> If I was staring at a bunch of blue / black text I wouldn't be as engaged.
> 
> I also do not see a problem with one design set of text on one page and another on another page.
> 
> My major complaint with the blog was that it was very cluttered and it was difficult to get through to the information, but in that case it was because of the type of blog that was being created.
> 
> Like it or not, a blog is not designed like a newsletter.
> 
> You can't have a block of text all in one section, but it needs to be easy to find what you are looking for and to get

what

**Comment by floppydisk05** [comment]
https://app.inferkit.com/demo
:kek:

**Comment by xproot** [comment]
image

**Comment by floppydisk05** [comment]
@CamK06 tell me why or I delete ankles with laser gun

**Comment by nick99nack** [comment]
@CamK06 we need this pr

**Comment by nick99nack** [comment]
@floppydisk05 bed

**Comment by floppydisk05** [comment]
yes

**Comment by floppydisk05** [comment]
@nick99nack bed

**Comment by xproot** [comment]
@nick99nack

**Comment by nick99nack** [comment]
no

**Comment by floppydisk05** [comment]
babe

**Comment by floppydisk05** [comment]
WAIT FUCK

**Comment by floppydisk05** [comment]
nooo

**Comment by xproot** [comment]
image
@floppydisk05

**Comment by xproot** [comment]
should have made it clear that it was talking about the original colors and not your pr

**Comment by floppydisk05** [comment]
@CamK06 literally h

**Comment by nick99nack** [comment]
hmm
maybe I'll make a new pr

**Comment by floppydisk05** [comment]
no

**Comment by nick99nack** [comment]
pr go

**Comment by floppydisk05** [comment]
my pr
my idea
smh

**Comment by floppydisk05** [comment]
banbe

**Comment by nick99nack** [comment]
I'm stealing your idea, maybe it'll get accepted

**Comment by floppydisk05** [comment]
shut

**Comment by xproot** [comment]
image

**Comment by floppydisk05** [comment]
I want credit

**Comment by nick99nack** [comment]
I'll give you credit, in my pr lol

**Comment by xproot** [comment]
floppy

> I want credit

one question, did you make this pr because you wanted credit
answer honestly

**Comment by floppydisk05** [comment]
image

**Comment by floppydisk05** [comment]
no. I made it because the colors I suggested are better

**Comment by nick99nack** [comment]
floppy go to bed

**Comment by xproot** [comment]
> no. I made it because the colors I suggested are better

(they're not tho)

**Comment by nick99nack** [comment]
but they are

**Comment by nick99nack** [comment]
they're less bright

**Comment by xproot** [comment]
and with that they look smushy, please choose a better color, also floppy doesn't wanna use custom colors (a.k.a colors not defined in DiscordColor, reducing his selection to the worst-est colors of all time. [I would certantly not smoke any cig if australia put these colors in their box instead of the color they have now](https://en.wikipedia.org/wiki/Pantone_448_C)

**Comment by xproot** [comment]
i have honestly insulted these colors in a lot of ways and i don't feel bad (except for orange), green is the worstest of all of them and green is my favorite color.

**Comment by floppydisk05** [comment]
I'm going to submit a another pr and change these colours by adding one to the R value

**Comment by floppydisk05** [comment]
also how dare you insult `DiscordColor.Aquamarine`

**Comment by CamK06** [comment]
yeah these colours suck.

**Comment by floppydisk05** [comment]
how

**Comment by floppydisk05** [comment]
fuck why can I not reopen this shit

**Pull request closed without merging**
