### PR TITLE
BREBT coMMEND

### PR DESCRIPTION
**Pull request by xproot**
breb

### CODE REVIEW

**Comment by nick99nack** [comment]
BRETT COMAN

**Comment by xproot** [comment]
STARMAN WHEN BREB

**Comment by HIDEN64** [comment]
AADD BRET

**Comment by xproot** [comment]
Are you pro-brent or anti-brent?

**Comment by floppydisk05** [comment]
@CamK06 BREBt COMMnand

**Comment by nick99nack** [comment]
BRENT COMAMDN

**Comment by floppydisk05** [comment]
no

**Comment by floppydisk05** [comment]
we need brANT commEN

**Comment by xproot** [comment]
CameraK06 why

**Comment by floppydisk05** [comment]
@xproot make another pr smh

**Comment by floppydisk05** [comment]
we need brant commend

**Comment by xproot** [comment]
u do it

**Comment by xproot** [comment]
@floppydisk05 make qanother pr smh

**Comment by floppydisk05** [comment]
@xproot it's ur pr smh

**Comment by xproot** [comment]
@floppydisk05 sleep smh

**Comment by xproot** [comment]
and what i meant is make a better brent command

**Comment by floppydisk05** [comment]
berbt coMEND

**Pull request closed without merging**
