### PR TITLE
Add more forbidden emojis to AntiYudsNortoningAutoModerationOfTheNort…

### PR DESCRIPTION
**Pull request by xproot**
…onsPostedByTheUserCalledYuds.cs

### CODE REVIEW

**Review by xproot — COMMENTED** [review]
Gud pls ad

**Comment by floppydisk05** [comment]
> Gud pls ad

tfw you review your own pr

**Comment by xproot** [comment]
> > Gud pls ad
> 
> tfw you review your own pr

review it for me then u noob 
### NOOOB

**Comment by xproot** [comment]
someone close this

**Comment by floppydisk05** [comment]
close it yourself you melon

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by StarX-2401** [comment]
h

**Comment by HIDEN64** [comment]
solve your conflicts mate

**Comment by xproot** [comment]
no

**Pull request closed without merging**
