### PR TITLE
ADD THE BRENT

### PR DESCRIPTION
**Pull request by xproot**
ADD IT
image

### CODE REVIEW

**Comment by xproot** [comment]
add it

**Comment by floppydisk05** [comment]
yes this is very important starman add it or I will hack into your computer and play raffi 25/7

**Comment by nick99nack** [comment]
.brent command

**Comment by xproot** [comment]
it still works probnably
ADD THE BERENT

**Comment by floppydisk05** [comment]
brebt comman

**Comment by xproot** [comment]
brabe

**Comment by floppydisk05** [comment]
brente comabne

**Comment by xproot** [comment]
**b r e n t**

**Comment by xproot** [comment]
where brentbe babe commanbabe

**Comment by xproot** [comment]
frick

**Comment by xproot** [comment]
Closed to fix up the branches, see #id when I readd it.

**Pull request closed without merging**
