### PR TITLE
Correct length error message

### PR DESCRIPTION
**Pull request by floppydisk05**
Timer length must be greater than 1, not 0

### CODE REVIEW

**Comment by nick99nack** [comment]
This makes no sense.

**Comment by floppydisk05** [comment]
> This makes no sense.

@nick99nack what

**Comment by floppydisk05** [comment]
if you attempt to use any time under 1 like 0.5 or 0.7, it errors saying it needs to be above 0

**Comment by nick99nack** [comment]
But you can use 1. So that's not greater than 1. You could say it has to be an integer greater than 0, but not greater than 1.

**Comment by floppydisk05** [comment]
@nick99nack I hate u

**Comment by CamK06** [comment]
Doesn't matter smh

**Pull request closed without merging**
