### PR TITLE
de-YanDev the HTTP cat command code

### PR DESCRIPTION
**Pull request by HIDEN64**

### CODE REVIEW

**Comment by CamK06** [comment]
404 functionality is a bit important... I'll just leave this opened until that's figured out, otherwise it's just taking away functionality (albeit minor functionality but still)

**Comment by codedipper** [comment]
An invalid code will result in the page returning a 404 status code, and the 404 image.
Because of the bug, I assume Discord won't accept images if it returns a 404 status code.

Only way I can think of resolving it, is to download the image and then send it directly.
But that's a horrible way to do it.

**Comment by CamK06** [comment]
Closing due to lack of a resolution to functionality issue

**Comment by xproot** [comment]
Array isn't so yandaredev...
It's actually a nicer solution than switch statements or if elses.

**Comment by xproot** [comment]
Actually a nicer solution would just be not checking if the HTTP code is valid at all, since it gives a 404 Reply with the 404 Image.
You could also check if the reply code isn't 2**

**Comment by xproot** [comment]
I am an absolute idiot and it doesn't embed without a valid code. so you need to fetch it for a better solution.

**Pull request closed without merging**
