### PR TITLE
Add a 8ball command.

### PR DESCRIPTION
**Pull request by xproot**
if you cancel my pull request then ~~get ded~~ tell me why.

There are 20 possible answers, 10 "affirmative", 5 "non-committal", and 5 "negative" [like an original 8-ball.](https://en.wikipedia.org/wiki/Magic_8-Ball#:~:text=A%20standard%20Magic%208%20Ball%20has%2020%20possible%20answers%2C%20including%2010%20affirmative%20answers%20(%E2%97%8F)%2C%205%20non%2Dcommittal%20answers%20(%E2%97%8F)%2C%20and%205%20negative%20answers%20(%E2%97%8F).)

## Help Info
image
## Example of usage, "Affirmative" answer
image
## Example of usage, "Non-committal" answer
image
## Example of usage, "Negative" answer
image

### CODE REVIEW

**Comment by SashiDegodeshi** [comment]
No.

**Comment by xproot** [comment]
> No.

yes

**Comment by nick99nack** [comment]
image

**Comment by xproot** [comment]
> DON'T COUNT ON IT.
sad

**Comment by floppydisk05** [comment]
no

**Comment by xproot** [comment]
> no

image

**Comment by CamK06** [comment]
Remove unnecessary brackets when checking the dex value, or find another way to do that. Or perhaps don't bother with that functionality

**Comment by xproot** [comment]
made my month
first c# lines ever written (if you don't count visual c#)
lets go

**Pull request merged**
