### PR TITLE
Add reminders list to remind command

### PR DESCRIPTION
**Pull request by floppydisk05**
Adds a reminder list to the remind command, accessed with `.remind list`
Some things could probably still be improved (e.g. usage)

### Example
image

### CODE REVIEW

**Comment by floppydisk05** [comment]
Another issue is that it errors if there are reminders with no text, which I'll fix later

**Comment by dkay0670** [comment]
smh  m e r g e

**Comment by codedipper** [comment]
> smh m e r g e

He's doing nerd radio stuff.

**Comment by dkay0670** [comment]
Yea

**Comment by floppydisk05** [comment]
pff neeeerrrddd

**Pull request merged**
