### PR TITLE
Improved 8ball embed colors

### PR DESCRIPTION
**Pull request by floppydisk05**

### CODE REVIEW

**Comment by CamK06** [comment]
Just stop.

**Comment by floppydisk05** [comment]
That is the most retarded reason to reject a pr I've ever seen.

**Comment by CamK06** [comment]
It's the same as the last one. I don't like the colours so it ain't happening, it's my bot. Put the colours in your own and leave it at that

**Comment by floppydisk05** [comment]
.

**Comment by floppydisk05** [comment]
well fuck you too.

**Pull request closed without merging**
